Converted getResourceById API call to DB retrieval
racker/salus-telemetry-presence-monitor pull request #59
Opened 2020-09-09 12:39 UTC by rohitsngh27

# Resolves
https://jira.rax.io/browse/SALUS-1014

# What
Converted getResourceById API call to DB retrieval

# How
Create a method which converts simple DB requests to DTO

## How to test
This can be tested by unit test cases

2020-09-09 16:16 UTC, itzg submitted a review, later dismissed

2020-09-09 17:37 UTC, jjbuchan requested changes
One small change

2020-09-09 17:37 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/telemetry/presence_monitor/services/ResourceListener.java
> +        return resource == null ? null : new ResourceDTO(resource, null);
I think Geoff also suggested this improvement in another PR.

```suggestion
        return resourceRepository.findByTenantIdAndResourceId(tenantId, resourceId)
            .map(resource -> new ResourceDTO(resource, null))
            .orElse(null);
```

2020-09-09 17:38 UTC, rohitsngh27 commented on src/main/java/com/rackspace/salus/telemetry/presence_monitor/services/ResourceListener.java
> +        return resource == null ? null : new ResourceDTO(resource, null);
Yes....Will do this in all the other PRs

2020-09-10 17:48 UTC, itzg approved these changes

2020-09-10 18:20 UTC, jjbuchan approved these changes

2020-09-10 18:27 UTC, merged